manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: efogdev
      url-base: https://github.com/efogdev
    - name: efogtech
      url-base: https://github.com/efogtech
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: efogdev
      revision: zephyr-4.1
    - name: zmk-pointer-2s-mixer
      remote: efogdev
      revision: main
    - name: zmk-axis-clamper
      remote: efogdev
      revision: main
    - name: zmk-report-rate-limit
      remote: efogdev
      revision: main
    - name: zmk-ec11-ish-driver
      remote: efogdev
      revision: main
    - name: zmk-auto-hold
      remote: efogdev
      revision: main
    - name: zmk-trigger-on-boot
      remote: efogdev
      revision: main
    - name: zmk-behavior-follower
      remote: efogdev
      revision: main
    - name: zmk-keymap-shell
      remote: efogdev
      revision: main
    - name: zmk-acceleration-curves
      remote: efogdev
      revision: main
  self:
    path: config
